# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'

        uploads_filesystem:
#            adapter: 'aws'
#            # visibility: public # Make the uploaded file publicly accessible in S3
#            options:
#                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
#                bucket: '%env(AWS_S3_BUCKET_NAME)%'
#                streamReads: true

            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/images'

when@prod:
    flysystem:
        storages:
            uploads_filesystem:
                adapter: 'aws'
                # visibility: public # Make the uploaded file publicly accessible in S3
                options:
                    client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
                    bucket: '%env(AWS_S3_BUCKET_NAME)%'
                    streamReads: true

#        uploads_filesystem:
#            adapter: 'aws'
#            # visibility: public # Make the uploaded file publicly accessible in S3
#            options:
#                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
#                bucket: '%env(AWS_S3_BUCKET_NAME)%'
##                prefix: 'optional/path/prefix'
#                streamReads: true

#    adapters:
#        uploads_adapter:
#            awss3v3:
#                client:
#                bucket: '%env(AWS_S3_BUCKET_NAME)%'
#
#    filesystems:
#        uploads_filesystem:
#            adapter: uploads_adapter
#
#        cached_uploads_filesystem:
#            adapter: uploads_adapter
##            cache: psr6_app_cache
